# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb

# Welcome to Colab!
"""

import sqlite3
import pandas as pd
import matplotlib.pyplot as plt

# Connect SQLite Database
conn = sqlite3.connect("sales_data.db")

# SQL Query 1
query1 = """
SELECT
    Category,
    SUM(Sales) AS Total_Revenue
FROM sales
GROUP BY Category
ORDER BY Total_Revenue DESC
"""

df = pd.read_sql_query(query1, conn)

print("Revenue by Category")
print(df)

# Bar Chart
plt.figure(figsize=(8,5))
plt.bar(df["Category"], df["Total_Revenue"])

plt.title("Revenue by Category")
plt.xlabel("Category")
plt.ylabel("Revenue")

plt.tight_layout()
plt.savefig("sales_chart.png")

plt.show()

# SQL Query 2
query2 = """
SELECT
    Category,
    SUM(Quantity) AS Total_Quantity
FROM sales
GROUP BY Category
ORDER BY Total_Quantity DESC
"""

qty_df = pd.read_sql_query(query2, conn)

print("\nTotal Quantity Sold")
print(qty_df)

conn.close()