# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb

# Welcome to Colab!
"""

import pandas as pd
import sqlite3

# Load CSV
df = pd.read_csv("/content/Sample - Superstore.csv", encoding="latin1")

# Create SQLite Database
conn = sqlite3.connect("sales_data.db")

# Store data in SQLite table
df.to_sql("sales", conn, if_exists="replace", index=False)

conn.close()

print("Database Created Successfully!")